// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnlEcjIiCyV2UpX3G-ei0LojoCy6C4N8E',
    appId: '1:327191753477:web:481885a4f53f8dd6f83d6c',
    messagingSenderId: '327191753477',
    projectId: 'fir-3-10032',
    authDomain: 'fir-3-10032.firebaseapp.com',
    storageBucket: 'fir-3-10032.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIgM-qs5DXcs-ef7-1BOC-9_XEHPoJ_dw',
    appId: '1:327191753477:android:ab78c8a9cbd3ecaef83d6c',
    messagingSenderId: '327191753477',
    projectId: 'fir-3-10032',
    storageBucket: 'fir-3-10032.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7l5cZgiNIq_sWmthqqpDvj79s1HS_7mU',
    appId: '1:327191753477:ios:c80d6083d71f2a6ff83d6c',
    messagingSenderId: '327191753477',
    projectId: 'fir-3-10032',
    storageBucket: 'fir-3-10032.appspot.com',
    iosBundleId: 'com.example.flutterFirebaseCrud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7l5cZgiNIq_sWmthqqpDvj79s1HS_7mU',
    appId: '1:327191753477:ios:c80d6083d71f2a6ff83d6c',
    messagingSenderId: '327191753477',
    projectId: 'fir-3-10032',
    storageBucket: 'fir-3-10032.appspot.com',
    iosBundleId: 'com.example.flutterFirebaseCrud',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnlEcjIiCyV2UpX3G-ei0LojoCy6C4N8E',
    appId: '1:327191753477:web:560ffbfd0e919811f83d6c',
    messagingSenderId: '327191753477',
    projectId: 'fir-3-10032',
    authDomain: 'fir-3-10032.firebaseapp.com',
    storageBucket: 'fir-3-10032.appspot.com',
  );
}
